name: Run Tests on Chrome and Firefox with Allure Report

on:
  push:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Google Chrome
        if: matrix.browser == 'chrome'
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Firefox and Geckodriver
        if: matrix.browser == 'firefox'
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest on ${{ matrix.browser }}
        run: pytest --browser=${{ matrix.browser }} --alluredir=allure-results-${{ matrix.browser }}

      - name: Upload Allure results for ${{ matrix.browser }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results-${{ matrix.browser }}
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download Allure results
        uses: actions/download-artifact@v4

      - name: Combine Allure results and generate report
        run: |
          mkdir combined-results
          cp -r allure-results-chrome/* combined-results/ || true
          cp -r allure-results-firefox/* combined-results/ || true
          allure generate -c combined-results -o _site

      - name: Upload combined report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site

  deploy-report:
    runs-on: ubuntu-latest
    needs: generate-report
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

